import type { InternalEntry } from "./entry-types";

export const INTERNAL_ENTRIES: InternalEntry[] = [
  {
    kind: "internal",
    id: "project-fda-redesign",
    slug: "fda-redesign",
    href: "/p/fda-redesign",
    hoverId: "work-fda",
    title: "Redesigning FDA’s Nutrition Facts Label",
    menuLabel: "UX Research Project: FDA Nutrition Facts",
    tag: "caseStudy",
    layout: "article",
    mdxPath: "app/p/fda-redesign/page.mdx",
    menu: {
      homeWorkOrder: 1,
      mobileFeaturedOrder: 1,
    },
    featured: {
      order: 1,
      title: "FDA NUTRITION FACTS LABEL",
      summary: "A redesign of the FDA's Nutrition Facts Label.",
      images: [
        "/fda-redesign/redesigned-nf.png",
        "/fda-redesign/original-nf.png",
      ],
      imageAlt: "A redesign of the FDA's Nutrition Facts Label.",
      actionText: "View Project",
    },
  },
  {
    kind: "internal",
    id: "project-lacima",
    slug: "lacima",
    href: "/p/lacima",
    hoverId: "work-lacima",
    title: "Web Design for La Cima Elementary",
    menuLabel: "Web Design for La Cima Elementary",
    tag: "education",
    layout: "article",
    mdxPath: "app/p/lacima/page.mdx",
    menu: {
      homeWorkOrder: 2,
      mobileFeaturedOrder: 2,
    },
    featured: {
      order: 2,
      title: "LA CIMA ELEMENTARY",
      summary: "A website redesign for La Cima Elementary.",
      images: ["/featured/lacima.png"],
      imageAlt: "A website redesign for La Cima Elementary.",
      actionText: "View Project",
    },
  },
  {
    kind: "internal",
    id: "project-seniorproject",
    slug: "seniorproject",
    href: "/p/seniorproject",
    hoverId: "work-senior",
    title: "Learning to Paint",
    menuLabel: "IDM@NYU Senior Project",
    tag: "experimentation",
    layout: "gallery",
    mdxPath: "app/p/seniorproject/page.mdx",
    menu: {
      homeWorkOrder: 3,
      mobileFeaturedOrder: 3,
    },
    featured: {
      order: 1,
      title: "LEARNING TO PAINT",
      summary: "A generative art installation built using L-systems.",
      images: ["/featured/seniorproject.png"],
      imageAlt: "A complex scramble of white dots on a black screen.",
      actionText: "View Project",
    },
  },
  {
    kind: "internal",
    id: "project-acc-final-project",
    slug: "acc-final-project",
    href: "/p/acc-final-project",
    hoverId: "work-acc",
    title: "ACC Project Proposal",
    menuLabel: "ACC Final Project",
    tag: "archive",
    layout: "article",
    mdxPath: "app/p/acc-final-project/page.mdx",
    menu: {
      mobileFeaturedOrder: 4,
    },
  },
  {
    kind: "internal",
    id: "project-nightflirt",
    slug: "nightflirt",
    href: "/p/nightflirt",
    hoverId: "work-nightflirt",
    title: "Designing Interfaces for the Silver Screen",
    menuLabel: "Nightflirt Case Study",
    tag: "caseStudy",
    layout: "article",
    mdxPath: "app/p/nightflirt/page.mdx",
  },
];
